### ISSUE TITLE
cern-roll installation on rocks cluster version 6.2

### ISSUE THREAD

**Issue by sharmaprajesh** [sdsc/cern-roll#1]
I download this roll into my machine in /root/extraRoll/cern dir. After unzip the code, I executed the
command make, after many lines and some download, process is hang with following line:

...
::: Downloading http://forge.sdsc.edu/triton/cern/src/root/root_v6.02.05.source.tar.gz :::
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
curl: (22) The requested URL returned error: 404 Not Found
::: Verifying size of root_v6.02.05.source.tar.gz :::
/usr/bin/stat: cannot stat `root_v6.02.05.source.tar.gz': No such file or directory

I am new guy for rocks cluster and adding new roll, please help me.
Thanks

**Comment by tcooper** [comment]
Thanks for reporting... we'll have a look.

**Comment by jerrypgreenberg** [comment]
root_v6.02.05.source.tar.gz is there now

Jerry

**Comment by tcooper** [comment]
@sharmaprajesh, please try to build again and let us know if this is resolved for you.

**Comment by sharmaprajesh** [comment]
Thanks for reply,
I remove all previous files, and get fresh copy from github, and then make. 

# But now build break with following errors...

...
::: Unbundling root_v6.02.05.source.tar.gz :::

( \
            cd root-6.02.05;   \
            ./configure --prefix=/opt/cern/root --with-xpm-libdir=/usr/lib64 --enable-minuit2 --enable-builtin-pcre;  \
            make;  \
    )
Checking for source directory ... /root/extraRoll/cern/cern-roll-master/BUILD/root-6.02.05/root-6.02.05
Configuring for linuxx8664gcc
Checking for GNU Make version >= 3.80 ... ok
Checking for C compiler ... gcc
Checking for C++ compiler ... g++
Checking for linker (LD) ... g++
Checking for F77 compiler ... gfortran
Checking whether c++11 mode is supported ... no
configure: c++11 mode is requested but the current compiler does not support it.
make[5]: Entering directory `/root/extraRoll/cern/cern-roll-master/BUILD/root-6.02.05/root-6.02.05'
Makefile:20: config/Makefile.config: No such file or directory
Makefile:36: config/Makefile.comp: No such file or directory
Makefile:47: *** Please run ./configure first.  Stop.
make[5]: Leaving directory`/root/extraRoll/cern/cern-roll-master/BUILD/root-6.02.05/root-6.02.05'
make[4]: **\* [build] Error 2
make[4]: Leaving directory `/root/extraRoll/cern/cern-roll-master/BUILD/root-6.02.05'
make[3]: *** [build] Error 2
make[3]: Leaving directory`/root/extraRoll/cern/cern-roll-master/BUILD/root-6.02.05'
error: Bad exit status from /var/tmp/rpm-tmp.QXwOTB (%build)

RPM build errors:
    Bad exit status from /var/tmp/rpm-tmp.QXwOTB (%build)
make[2]: **\* [rpm] Error 1
make[2]: Leaving directory `/root/extraRoll/cern/cern-roll-master/src/root'
make[1]: *** [rpm] Error 2
make[1]: Leaving directory`/root/extraRoll/cern/cern-roll-master/src'
make: **\* [rpms] Error 2

#

**Comment by tcooper** [comment]
Do you have the gnu-roll and gnucompiler-roll built and installed on your build machine?

**Comment by sharmaprajesh** [comment]
thanks for reply,
I have installed sdsc, cmake and    gnutools, but during  gnucompiler-roll build i have also some problem.
I wrote it on your's gnucompiler-roll issue.

**Comment by sharmaprajesh** [comment]
now, i have install gnu compiler roll successfully. But I did not find "gnu roll" because  there is no roll name gnu-roll in sdsc repository.Both links provided by you on cern roll page in  README.md file for "gnu roll" and  "gnu compiler roll" reference to "gnu compiler roll" page.
sir, please provide installation steps for cern roll as provided with other roll's installation.
Thank you.

**Comment by jjhayes** [comment]
"gnu roll" is an old name for what is now the gnutools-roll.  It doesn't look like the cern-roll needs gnutools, though, so I don't think you need to install it.  The cern build does use cmake, though.  Although the cmake-roll will only be needed if the cern make process uses some advanced cmake features, you should probably download, build, and install the cmake-roll.

It looks like you've uncovered a bug in the root package Makefile.  I'm working on a fix now.

**Comment by tcooper** [comment]
@sharmaprajesh, this should be fixed in the [latest commit](https://github.com/sdsc/cern-roll/commit/9381d96).

**Comment by sharmaprajesh** [comment]
Thanks for your previous help. I have installed sdsc,cmake, and gnucompiler roll, But when i make
cern roll , after taking some time it crash after the following display:
------->include/TSQLiteResult.h:20:10: fatal error: 'sqlite3.h' file not found

did I left/missed something? sir, please help me.

I have included some last lines of the output:
Generating dictionary math/quadp/src/G__Quadp.cxx...
bin/rootcling -rootbuild -f math/quadp/src/G__Quadp.cxx -s lib/libQuadp.so -rml libQuadp.so -rmf lib/libQuadp.rootmap -m lib/libCore_rdict.pcm -m lib/libMatrix._rdict.pcm -c /state/partition1/cern/cern-roll-master/BUILD/sdsc-root-6.02.05/root-6.02.05/math/quadp/inc/TGondzioSolver.h /state/partition1/cern/cern-roll-master/BUILD/sdsc-root-6.02.05/root-6.02.05/math/quadp/inc/TMehrotraSolver.h /state/partition1/cern/cern-roll-master/BUILD/sdsc-root-6.02.05/root-6.02.05/math/quadp/inc/TQpDataBase.h /state/partition1/cern/cern-roll-master/BUILD/sdsc-root-6.02.05/root-6.02.05/math/quadp/inc/TQpDataDens.h /state/partition1/cern/cern-roll-master/BUILD/sdsc-root-6.02.05/root-6.02.05/math/quadp/inc/TQpDataSparse.h /state/partition1/cern/cern-roll-master/BUILD/sdsc-root-6.02.05/root-6.02.05/math/quadp/inc/TQpLinSolverBase.h /state/partition1/cern/cern-roll-master/BUILD/sdsc-root-6.02.05/root-6.02.05/math/quadp/inc/TQpLinSolverDens.h /state/partition1/cern/cern-roll-master/BUILD/sdsc-root-6.02.05/root-6.02.05/math/quadp/inc/TQpLinSolverSparse.h /state/partition1/cern/cern-roll-master/BUILD/sdsc-root-6.02.05/root-6.02.05/math/quadp/inc/TQpProbBase.h /state/partition1/cern/cern-roll-master/BUILD/sdsc-root-6.02.05/root-6.02.05/math/quadp/inc/TQpProbDens.h /state/partition1/cern/cern-roll-master/BUILD/sdsc-root-6.02.05/root-6.02.05/math/quadp/inc/TQpProbSparse.h /state/partition1/cern/cern-roll-master/BUILD/sdsc-root-6.02.05/root-6.02.05/math/quadp/inc/TQpResidual.h /state/partition1/cern/cern-roll-master/BUILD/sdsc-root-6.02.05/root-6.02.05/math/quadp/inc/TQpSolverBase.h /state/partition1/cern/cern-roll-master/BUILD/sdsc-root-6.02.05/root-6.02.05/math/quadp/inc/TQpVar.h /state/partition1/cern/cern-roll-master/BUILD/sdsc-root-6.02.05/root-6.02.05/math/quadp/inc/LinkDef.h
bin/rmkdepend -R -fgeom/geom/src/G__Geom.d -Y -w 1000 -- -pipe -m64 -Wshadow -Wall -W -Woverloaded-virtual -fPIC -Iinclude -DR__HAVE_CONFIG -std=c++11 -Wno-deprecated-declarations -pthread -D__cplusplus -- geom/geom/src/G__Geom.cxx
g++  -pipe -m64 -Wshadow -Wall -W -Woverloaded-virtual -fPIC -Iinclude -DR__HAVE_CONFIG -std=c++11 -Wno-deprecated-declarations -pthread -I. -o geom/geom/src/G__Geom.o -c geom/geom/src/G__Geom.cxx
In file included from input_line_12:6:
include/TSQLiteResult.h:20:10: fatal error: 'sqlite3.h' file not found
#include <sqlite3.h>
         ^
Error: bin/rootcling: compilation failure (lib/libRSQLitef869e96740_dictUmbrella.h)
make[5]: **\* [sql/sqlite/src/G__SQLite.cxx] Error 1
make[5]: **\* Waiting for unfinished jobs....
make[5]: Leaving directory `/state/partition1/cern/cern-roll-master/BUILD/sdsc-root-6.02.05/root-6.02.05'
make[4]: *** [build] Error 2
make[4]: Leaving directory`/state/partition1/cern/cern-roll-master/BUILD/sdsc-root-6.02.05'
make[3]: **\* [build] Error 2
make[3]: Leaving directory `/state/partition1/cern/cern-roll-master/BUILD/sdsc-root-6.02.05'
error: Bad exit status from /var/tmp/rpm-tmp.l3lfKR (%build)

RPM build errors:
    Bad exit status from /var/tmp/rpm-tmp.l3lfKR (%build)
make[2]: **\* [rpm] Error 1
make[2]: Leaving directory `/state/partition1/cern/cern-roll-master/src/root'
make[1]: *** [rpm] Error 2
make[1]: Leaving directory`/state/partition1/cern/cern-roll-master/src'
make: **\* [rpms] Error 2

**Comment by tcooper** [comment]
It appears you don't have the `sqlite` headers installed. We'll add this RPM to the dependency list in the README.md file for the roll.

Here is the general procedure to find missing dependencies (output slightly edited for brevity)...

#### Find which RPM provides the missing file

```
# yum whatprovides "*/sqlite3.h"
...<snip>...
sqlite-devel-3.6.20-1.el6.x86_64 : Development tools for the sqlite3 embeddable
                                 : SQL database engine
Repo        : Rocks-6.2
Matched from:
Filename    : /usr/include/sqlite3.h
...<snip>...
```

#### Install missing RPM

```
# yum install sqlite-devel
Setting up Install Process
Resolving Dependencies
--> Running transaction check
---> Package sqlite-devel.x86_64 0:3.6.20-1.el6 will be installed
--> Finished Dependency Resolution

Dependencies Resolved

===============================================================================
 Package             Arch          Version               Repository        Size
===============================================================================
Installing:
 sqlite-devel        x86_64        3.6.20-1.el6          Rocks-6.2         81 k

Transaction Summary
===============================================================================
Install       1 Package(s)

Total download size: 81 k
Installed size: 283 k
Is this ok [y/N]: y
Downloading Packages:
sqlite-devel-3.6.20-1.el6.x86_64.rpm                     |  81 kB     00:00
Running rpm_check_debug
Running Transaction Test
Transaction Test Succeeded
Running Transaction
  Installing : sqlite-devel-3.6.20-1.el6.x86_64                             1/1
  Verifying  : sqlite-devel-3.6.20-1.el6.x86_64                             1/1

Installed:
  sqlite-devel.x86_64 0:3.6.20-1.el6

Complete!
```

#### Verify file is installed

```
# whereis sqlite3.h
sqlite3: /usr/bin/sqlite3 /usr/include/sqlite3.h /opt/sqlite/bin/sqlite3 /usr/share/man/man1/sqlite3.1.gz
```

**Comment by sharmaprajesh** [comment]
Thank you very much Sir, I installed cern roll successfully.
